name: zzk

on:
  workflow_dispatch:
  schedule:
     - cron: 51 6,13 * * *
jobs:
  build:
    runs-on: ubuntu-latest    
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install
          npm install cron
          npm install request
      - name: '运行 【kkz】'
        run: |
          node jqkkhear.js
    
